import pandas as pd


def get_customer_metrics(df):
    """
    Customer-related KPIs
    """

    total_customers = df["Customer_ID"].nunique()

    total_orders = df["Order_ID"].nunique()

    avg_orders_per_customer = round(
        total_orders / total_customers, 2
    ) if total_customers > 0 else 0

    customer_revenue = (
        df.groupby("Customer_Name")["Revenue"]
        .sum()
        .reset_index()
        .sort_values(by="Revenue", ascending=False)
    )

    top_customers = customer_revenue.head(10)

    return {
        "total_customers": total_customers,
        "avg_orders_per_customer": avg_orders_per_customer,
        "top_customers": top_customers
    }


def new_vs_returning_customers(df):
    """
    New vs Returning Customers
    """

    customer_orders = (
        df.groupby("Customer_ID")["Order_ID"]
        .nunique()
        .reset_index()
    )

    new_customers = len(
        customer_orders[customer_orders["Order_ID"] == 1]
    )

    returning_customers = len(
        customer_orders[customer_orders["Order_ID"] > 1]
    )

    return pd.DataFrame({
        "Customer Type": ["New Customers", "Returning Customers"],
        "Count": [new_customers, returning_customers]
    })


def customer_revenue_analysis(df):
    """
    Revenue generated by each customer
    """

    revenue_df = (
        df.groupby("Customer_Name")["Revenue"]
        .sum()
        .reset_index()
        .sort_values(by="Revenue", ascending=False)
    )

    return revenue_df


def top_10_customers(df):
    """
    Top 10 customers by revenue
    """

    return (
        df.groupby("Customer_Name")["Revenue"]
        .sum()
        .reset_index()
        .sort_values(by="Revenue", ascending=False)
        .head(10)
    )


def customer_order_frequency(df):
    """
    Number of orders placed by customers
    """

    frequency_df = (
        df.groupby("Customer_Name")["Order_ID"]
        .nunique()
        .reset_index()
        .rename(columns={"Order_ID": "Total Orders"})
        .sort_values(by="Total Orders", ascending=False)
    )

    return frequency_df