import pandas as pd


def get_product_metrics(df):
    """
    Product-related KPIs
    """

    total_products = df["Product"].nunique()

    total_categories = df["Category"].nunique()

    return {
        "total_products": total_products,
        "total_categories": total_categories
    }


def top_selling_products(df, top_n=10):
    """
    Top products by revenue
    """

    top_products = (
        df.groupby("Product")["Revenue"]
        .sum()
        .reset_index()
        .sort_values(by="Revenue", ascending=False)
        .head(top_n)
    )

    return top_products


def top_products_by_quantity(df, top_n=10):
    """
    Top products by quantity sold
    """

    quantity_df = (
        df.groupby("Product")["Quantity"]
        .sum()
        .reset_index()
        .sort_values(by="Quantity", ascending=False)
        .head(top_n)
    )

    return quantity_df


def lowest_selling_products(df, bottom_n=10):
    """
    Lowest products by revenue
    """

    bottom_products = (
        df.groupby("Product")["Revenue"]
        .sum()
        .reset_index()
        .sort_values(by="Revenue", ascending=True)
        .head(bottom_n)
    )

    return bottom_products


def category_performance(df):
    """
    Category-wise revenue and profit
    """

    category_df = (
        df.groupby("Category")
        .agg({
            "Revenue": "sum",
            "Profit": "sum",
            "Quantity": "sum"
        })
        .reset_index()
        .sort_values(by="Revenue", ascending=False)
    )

    return category_df


def product_profit_analysis(df, top_n=10):
    """
    Most profitable products
    """

    profit_df = (
        df.groupby("Product")["Profit"]
        .sum()
        .reset_index()
        .sort_values(by="Profit", ascending=False)
        .head(top_n)
    )

    return profit_df


def product_revenue_analysis(df):
    """
    Revenue generated by each product
    """

    revenue_df = (
        df.groupby("Product")["Revenue"]
        .sum()
        .reset_index()
        .sort_values(by="Revenue", ascending=False)
    )

    return revenue_df


def category_quantity_analysis(df):
    """
    Quantity sold by category
    """

    quantity_df = (
        df.groupby("Category")["Quantity"]
        .sum()
        .reset_index()
        .sort_values(by="Quantity", ascending=False)
    )

    return quantity_df